name: "deploy"

on: 
  push:
    branches: [main, prod]

jobs:
  gapp-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    environment:
      name: ${{ github.ref_name }}

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3

    - name: "Print stuff"
      run: echo ${{ github.ref }} ${{ github.ref_name }}

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        working_directory: ${{ github.workspace }}
        deliverables: ${{ vars.GOOGLE_APPENGINE_YAML_PATH }}
        
    - name: "Check deployment"
      run: 'curl "${{ steps.deploy.outputs.url }}"'
