name: "deploy"

on: 
  push:
    branches: [main]

jobs:
  gapp-engine:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        deliverables: app.yaml
        
