name: "deploy"

on: 
  push:
    branches: [main]

jobs:
  gapp-engine:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCLOUD_CREDENTIALS_JSON }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'
      with:
        working_directory: ${{ github.workspace }}
        deliverables: app.prod.yaml
        
    - name: "Check deployment"
      run: 'curl "${{ steps.deploy.outputs.url }}"'
